apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  label: 
    role: webservice
    run: my-nginx
spec:
  ports:
    - name: HTTP
      port: 8080
      protocol: TCP
      targetPort: 80
    - name: HTTPS
      port: 8443
      protocol: TCP
      targetPort: 443
  selector:
    run: my-name